### ISSUE TITLE
V 1.19 Aternos. My server crashed and won't start anymore! 

### ISSUE THREAD

**Issue by BeastMaster6989** [finallion/The-Graveyard-FORGE-#45] opened 2022-07-08 10:05 UTC
### What's the issue you encountered?

My server crashed and won't start anymore. Up to a certain point, everything worked fine, then the server crashed and no longer works. I don't know what caused the crash.

### How can the issue be reproduced?

Create a server -> download a mod -> get a server crash

### Logs

https://mclo.gs/8TqSj4c

**Comment by finallion** [comment] 2022-07-08 12:30
Probably caused by the newest forge version changing something. I therefor need to update the mod. The best to fix this issue for now is using the same forge version you were using before updating.

**Comment by finallion** [comment] 2022-08-01 12:59
Fixed in 1.11.

**Closed as completed by finallion** 2022-08-01 12:59 UTC
Labels: bug
